# Generated by Django 2.2.7 on 2020-01-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accident',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.IntegerField()),
                ('time', models.DateTimeField(verbose_name='Time of accident')),
                ('vehicleinfo', models.CharField(max_length=1000)),
                ('deviceinfo', models.CharField(max_length=1000)),
                ('accelerometerX', models.CharField(default='', max_length=10000)),
                ('rotationX', models.CharField(default='', max_length=10000)),
                ('accelerometerY', models.CharField(default='', max_length=10000)),
                ('rotationY', models.CharField(default='', max_length=10000)),
                ('accelerometerZ', models.CharField(default='', max_length=10000)),
                ('rotationZ', models.CharField(default='', max_length=10000)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='authority',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('authoritytype', models.CharField(choices=[('hospital', 'Hospital'), ('police', 'Police Station'), ('fire', 'Fire Station'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
    ]
