# Generated by Django 2.2.7 on 2020-01-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='accelerometerX',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accelerometerY',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accelerometerZ',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accident',
            name='deviceinfo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accident',
            name='rotationX',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accident',
            name='rotationY',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accident',
            name='rotationZ',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accident',
            name='vehicleinfo',
            field=models.TextField(),
        ),
    ]
