# Generated by Django 2.2.7 on 2020-01-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200115_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='deviceinfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
