# Generated by Django 2.2.7 on 2020-01-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20200118_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='vehicleinfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
