# Generated by Django 2.2.7 on 2020-01-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20200118_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='uid',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
