# Generated by Django 2.2.7 on 2020-01-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20200118_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='pincode',
            field=models.CharField(default=560059, max_length=10),
            preserve_default=False,
        ),
    ]
