# Generated by Django 2.2.7 on 2020-01-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_accident_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='authoritytype',
            field=models.CharField(choices=[('hospital', 'hospital'), ('police', 'police'), ('fire', 'fire'), ('other', 'other')], default='other', max_length=20),
        ),
    ]
